#!/usr/bin/env bash
# JP 跳板/最小开发环境：只创建目录和 shell PATH，不放 AI 工具和密钥环境。

PROFILE_NAME="minimal"
INSTALL_USER_DIRS="${INSTALL_USER_DIRS:-1}"
INSTALL_SHELL_PROFILE="${INSTALL_SHELL_PROFILE:-1}"
INSTALL_NODE_FNM="${INSTALL_NODE_FNM:-0}"
INSTALL_CODEX_CLI="${INSTALL_CODEX_CLI:-0}"
INSTALL_CC_SWITCH_CLI="${INSTALL_CC_SWITCH_CLI:-0}"
INSTALL_FOUNDRY="${INSTALL_FOUNDRY:-0}"
INSTALL_RUST="${INSTALL_RUST:-0}"
INSTALL_PYTHON_UV="${INSTALL_PYTHON_UV:-0}"
INSTALL_ZK_TOOLS="${INSTALL_ZK_TOOLS:-0}"
INSTALL_REMOTE_COMPUTE="${INSTALL_REMOTE_COMPUTE:-0}"
