#!/usr/bin/env bash
# US 重计算机：默认只安装计算/测试工具，不安装 AI provider 管理工具。

PROFILE_NAME="us-compute"
INSTALL_USER_DIRS="${INSTALL_USER_DIRS:-1}"
INSTALL_SHELL_PROFILE="${INSTALL_SHELL_PROFILE:-1}"
INSTALL_NODE_FNM="${INSTALL_NODE_FNM:-1}"
INSTALL_CODEX_CLI="${INSTALL_CODEX_CLI:-0}"
INSTALL_CC_SWITCH_CLI="${INSTALL_CC_SWITCH_CLI:-0}"
INSTALL_FOUNDRY="${INSTALL_FOUNDRY:-1}"
INSTALL_RUST="${INSTALL_RUST:-1}"
INSTALL_PYTHON_UV="${INSTALL_PYTHON_UV:-1}"
INSTALL_ZK_TOOLS="${INSTALL_ZK_TOOLS:-0}"
INSTALL_REMOTE_COMPUTE="${INSTALL_REMOTE_COMPUTE:-0}"

NODE_VERSION="${NODE_VERSION:-22}"
